## 신경망(Neural Net)의 구조
- Layers, 입력데이터/타겟(라벨), Loss Fucntion, Optimizer

## Layer
- Weight을 가지며
- Fully connected / Densely connected Lyaer
- Recurrent Layer
- Convolution Layer 등이 있음

## Model
- 이러한 Layer를 이용해 하나의 네트워크를 구성할 수 있고,
- 이는 Hypothesis Space를 정의하는 것

## Loss Function ; Objective Function
- 트레이닝 되는 동안 최소화 될 값을 출력함
- 문제에 맞는 **올바른 목적 함수를 선택하는 것이 중요**
- 기본 지침
    - 2개 클래스 분류 문제: binary crossentropy; logistic loss, log loss
    - n개 클래스 분류 문제: categorical crossentropy
    - Regression 문제: Mean Squared Error
    - Sequence 학습 문제: Connection Temporal Classification (CTC)
        - 음석 인식이나 필기 인식 처럼 입력에 레이블 할당 위치를 정하기 어려운 연속 시퀀스를 다루는 문제에 사용

## Optimizer
- Loss Function을 기반으로 네트워크가 어떻게 업데이트 되야할지 결정
- 여러 개의 출력을 내는 신경망도 있는데, 이는 여러 개의 Loss function을 가짐
    - 하지만 SGD는 하나의 스칼라 손실 값을 기준으로 동작하기 때문에
    - 모든 손실을 평균을 내 하나의 스칼라로 합쳐 계산함

In [6]:
import numpy as np
a = np.array([[1,2,3,4,], [5,6,7,8]])

In [7]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a[1,2] = 55
a

array([[ 1,  2,  3,  4],
       [ 5,  6, 55,  8]])

In [13]:
a[1,[2]] = 999
a

array([[  1,   2,   3,   4],
       [  5,   6, 999,   8]])