## ndarray

In [1]:
import numpy as np

In [3]:
data = np.random.randn(2, 3)
data

array([[-1.28796941,  0.39688115,  1.73256888],
       [-1.46066225, -0.80390333, -0.73047336]])

In [4]:
data * 10

array([[-12.87969414,   3.9688115 ,  17.32568881],
       [-14.60662249,  -8.0390333 ,  -7.30473362]])

In [5]:
data + data

array([[-2.57593883,  0.7937623 ,  3.46513776],
       [-2.9213245 , -1.60780666, -1.46094672]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

## Create ndarray

In [8]:
data1 = [6, 8.5 ,2, 4, 0, 1.1]

arr1 = np.array(data1)
arr1

array([6. , 8.5, 2. , 4. , 0. , 1.1])

In [10]:
arr1.dtype

dtype('float64')

In [11]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.empty((2,3,2))

array([[[6.95332539e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## data type of ndarray
- int, float
- bool
- object !!! (python object)
- string_, unicode_
- possible to change type
    - astype -> always create new array

In [19]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

In [20]:
print(arr1.dtype, arr2.dtype)

float64 int32


In [24]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [23]:
# change type
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [26]:
numeric_string = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_string.astype(float)

array([ 1.25, -9.6 , 42.  ])

## vector, scalar ops
- broadcasting : ops between arrays which have different sizes

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## Indexing & Slicing
- notice: all of the subset selected by indexing or slicing -> view of the original

In [33]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[5]

5

In [35]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr[5:8] = 12 # broadcasting, apply to the original directly, cf) ndarray.copy
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [49]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[2]

array([7, 8, 9])

In [50]:
arr2d[0,2], arr2d[0][2]

(3, 3)

In [51]:
old_values = arr2d[0].copy()
arr2d[0] = 0
arr2d

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2d[0] = old_values

In [53]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Slice Indexing

In [60]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [58]:
arr2d[1, :2]

array([4, 5])

In [59]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

### Boolean Indexing

In [87]:
names = np.array(['bob', 'Joe', 'Will', 'bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [88]:
names

array(['bob', 'Joe', 'Will', 'bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [89]:
data

array([[-0.44884915,  1.34997911, -0.05590612, -0.79396987],
       [-0.51199474,  0.44333533,  1.92668232,  0.75508294],
       [ 0.58734024,  0.23191033, -0.37900135, -0.29492434],
       [-0.10674729, -0.74844327,  0.91495416, -1.59118693],
       [ 0.04001221, -2.12614505, -1.32029667, -0.11876287],
       [-0.47360421, -0.49921125,  1.31036675, -1.04779195],
       [-0.68541908, -0.25450215, -1.57624755, -1.36775744]])

In [90]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [91]:
data[names == 'bob']

array([[-0.44884915,  1.34997911, -0.05590612, -0.79396987],
       [-0.10674729, -0.74844327,  0.91495416, -1.59118693]])

In [92]:
data[names == 'bob', 2:]

array([[-0.05590612, -0.79396987],
       [ 0.91495416, -1.59118693]])

In [93]:
names != 'bob'

array([False,  True,  True, False,  True,  True,  True])

In [94]:
mask = (names == 'bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [95]:
data[mask] = 7

In [96]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.51199474,  0.44333533,  1.92668232,  0.75508294],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.47360421, -0.49921125,  1.31036675, -1.04779195],
       [-0.68541908, -0.25450215, -1.57624755, -1.36775744]])

In [97]:
data[data < 0] = 0

In [98]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.44333533, 1.92668232, 0.75508294],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.31036675, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

### Fancy Indexing

In [103]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [104]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [105]:
arr = np.arange(32).reshape((8,4))

In [107]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [109]:
arr[[1,5,7,2], [0,3,1,2]] # ?????????????????????????

array([ 4, 23, 29, 10])

In [111]:
arr[[1,5,7,2]][:, [0,3,1,2]] # ooooooooooooooooooooooooo

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [112]:
arr[np.ix_([1,5,7,2], [0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### transpose

In [114]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [117]:
np.dot(arr.T, arr) # inner product

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

## Universal func
- 1params: abs, fabs, sqrt, square, Exp, Log, log10, log2, sign, ceil, floort, isnan, cos, sin, tan, tanh, ...
- 2params: add, subtract, multiply, dvide, power, maximum, ...

In [118]:
arr = np.arange(10)

In [119]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [120]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])